=== Pintass/php-tests/TP_XML/Voiliers.dtd
<!ELEMENT voiliers (voilier*)>
<!ATTLIST voiliers
        transat CDATA #REQUIRED
        >

<!ELEMENT voilier (nom, photo, skippers)>
    <!ATTLIST voilier
            Classe CDATA #REQUIRED
            Annee CDATA #REQUIRED
    >
<!ELEMENT nom (#PCDATA)>

<!ELEMENT photo (#PCDATA)>

<!ELEMENT skippers (skipper*)>

<!ELEMENT skipper (nom, origine)>

<!ATTLIST skipper
                age CDATA #REQUIRED
>
<!ELEMENT age (#PCDATA)>

<!ELEMENT origine (#PCDATA)>

=== Pintass/php-tests/TP_XML/Voiliers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE voiliers SYSTEM "Voiliers.dtd">
<voiliers transat="Café 2025">
  <voilier Classe="Ocean Fifty" Annee="2025">
    <nom>EDENRED 5</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-09/EDENRED-Ocean%20Fifty.JPG.webp?itok=8YErlYtU</photo>
    <skippers>
      <skipper age="53">
        <nom>Emmanuel LE ROCH</nom>
        <origine>Plouharnel</origine>
      </skipper>
      <skipper age="23">
        <nom>Basile BOURGNON</nom>
        <origine>Saint-Philibert</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Ocean Fifty" Annee="2023">
    <nom>INTER INVEST</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-09/INTER%20INVEST%20%20-%20OCEAN%20FIFTY.jpg.webp?itok=vp5doKgS</photo>
    <skippers>
      <skipper age="35">
        <nom>Matthieu PERRAUT</nom>
        <origine>Pornichet</origine>
      </skipper>
      <skipper age="37">
        <nom>Jean-Baptiste GELLÉE</nom>
        <origine>Pornichet</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Ocean Fifty" Annee="2023">
    <nom>KOESIO</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-07/KOESIO%20-%20Ocean%20Fifty.jpg.webp?itok=HyIGFE15</photo>
    <skippers>
      <skipper age="51">
        <nom>Erwan LE ROUX</nom>
        <origine>La Trinité sur Mer</origine>
      </skipper>
      <skipper age="33">
        <nom>Audrey OGEREAU</nom>
        <origine>La Ciotat</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Ocean Fifty" Annee="2023">
    <nom>Lazare x Hellio</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-07/lazare.jpg.webp?itok=uLH5UkxL</photo>
    <skippers>
      <skipper age="29">
        <nom>Erwan LE DRAOULEC</nom>
        <origine>Plouhinec</origine>
      </skipper>
      <skipper age="36">
        <nom>Tanguy LE TURQUAIS</nom>
        <origine>Locmiquelic</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Ocean Fifty" Annee="2009">
    <nom>LE RIRE MÉDECIN - LAMOTTE</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-08/LE%20RIRE%20MEDECIN%20-%20LAMOTTE%20-%20Ocean%20Fifty%202.png.webp?itok=DT3puNTP</photo>
    <skippers>
      <skipper age="39">
        <nom>Luke BERRY</nom>
        <origine>Saint Malo</origine>
      </skipper>
      <skipper age="39">
        <nom>Antoine JOUBERT</nom>
        <origine>Tours</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Ocean Fifty" Annee="?">
    <nom>MON BONNET ROSE</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/mon_bonnet_rose.jpg.webp?itok=ltiJYsvS</photo>
    <skippers>
      <skipper age="44">
        <nom>Laurent BOURGUES</nom>
        <origine>Marseille</origine>
      </skipper>
      <skipper age="45">
        <nom>Arnaud VASSEUR</nom>
        <origine>Fontenay aux roses</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Ocean Fifty" Annee="2020">
    <nom>SOLIDAIRES EN PELOTON</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-07/SOLIDAIRES%20EN%20PELOTON%20-%20Ocean%20Fifty.jpg.webp?itok=SHF5s_eo</photo>
    <skippers>
      <skipper age="47">
        <nom>Thibaut VAUCHEL-CAMUS</nom>
        <origine>Cancale</origine>
      </skipper>
      <skipper age="46">
        <nom>Damien SEGUIN</nom>
        <origine>Auray</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Ocean Fifty" Annee="?">
    <nom>UPWIND BY MERCONCEPT</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/upwind_by_merconcept.jpg.webp?itok=MbantxNz</photo>
    <skippers>
      <skipper age="43">
        <nom>Anne-Claire LE BERRE</nom>
        <origine>Brest</origine>
      </skipper>
      <skipper age="41">
        <nom>Elodie-Jane METTRAUX</nom>
        <origine>Neyruz</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Ocean Fifty" Annee="2017">
    <nom>VIABILIS OCEANS</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-08/VIABILIS%20OCEANS%20-%20Ocean%20fifty.jpg.webp?itok=1tEPrTK1</photo>
    <skippers>
      <skipper age="28">
        <nom>Baptiste HULIN</nom>
        <origine>La Tessoualle</origine>
      </skipper>
      <skipper age="43">
        <nom>Thomas ROUXEL</nom>
        <origine>St Brieuc</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Ocean Fifty" Annee="2019">
    <nom>WEWISE</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-09/WEWISE%20-%20OCEAN%20FIFTY.jpg.webp?itok=mVU3h3CV</photo>
    <skippers>
      <skipper age="33">
        <nom>Pierre QUIROGA</nom>
        <origine>La Capte</origine>
      </skipper>
      <skipper age="28">
        <nom>Gaston MORVAN</nom>
        <origine>Landeda</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Class40" Annee="2023">
    <nom>ALTERNATIVE SAILING- LES CONSTRUCTIONS DU BELON</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/alternative_sailing_-_les_constructions_de_belon.jpg.webp?itok=PYkuBV7v</photo>
    <skippers>
      <skipper age="32">
        <nom>Guillaume L'HOSTIS</nom>
        <origine>Brest</origine>
      </skipper>
      <skipper age="40">
        <nom>Antoine LE MANCHEC</nom>
        <origine>Chartres</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Class40" Annee="2022">
    <nom>ALDERAN</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/alderan.jpg.webp?itok=1JaFi1pB</photo>
    <skippers>
      <skipper age="32">
        <nom>Sasha LANIECE</nom>
        <origine>Paris</origine>
      </skipper>
      <skipper age="34">
        <nom>Sanni BEUCKE</nom>
        <origine>Kiel</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Class40" Annee="2019">
    <nom>AIRVANCE OCÉLIAN TERÉLIAN</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-10/AIRVANCE%20OC%C3%89LIAN%20TER%C3%89LIAN%20-%20Class40.jpg.webp?itok=HVxv8_z7</photo>
    <skippers>
      <skipper age="26">
        <nom>Théa KHELIF</nom>
        <origine>Calais</origine>
      </skipper>
      <skipper age="43">
        <nom>Marion ENGELHARD</nom>
        <origine>Havre</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Class40" Annee="2012">
    <nom>MARTINIQUE HORIZON</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-08/MARTINIQUE%20HORIZON%20-%20CLASS40.jpg.webp?itok=6tHUoQtS</photo>
    <skippers>
      <skipper age="40">
        <nom>Jean-Yves AGLAE</nom>
        <origine>Sainte-Luce</origine>
      </skipper>
      <skipper age="37">
        <nom>Moane MANGATTALE</nom>
        <origine>Le Lamentin</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Class40" Annee="2025">
    <nom>MACCAFERRI FUTURA</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-07/MACCAFERRI%20FUTURA%20-%20Class40.jpg.webp?itok=a6jXdbTx</photo>
    <skippers>
      <skipper age="30">
        <nom>Luca ROSETTI</nom>
        <origine>Bologne</origine>
      </skipper>
      <skipper age="28">
        <nom>Matteo SERICANO</nom>
        <origine>Genova </origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Class40" Annee="2024">
    <nom>LES INVINCIBLES</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-09/LES%20INVINCIBLES%20-%20Class40.jpg.webp?itok=agFVeXD5</photo>
    <skippers>
      <skipper age="32">
        <nom>William MATHELIN-MOREAUX</nom>
        <origine>Paris</origine>
      </skipper>
      <skipper age="40">
        <nom>Pietro LUCIANI</nom>
        <origine>Venise</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Class40" Annee="2023">
    <nom>LEGALLAIS</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/legallais.jpg.webp?itok=PZpSr1YI</photo>
    <skippers>
      <skipper age="41">
        <nom>Fabien DELAHAYE</nom>
        <origine>Larmor Plage</origine>
      </skipper>
      <skipper age="45">
        <nom>Pierre LEBOUCHER</nom>
        <origine>Nantes</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Class40" Annee="2018">
    <nom>L'AGENCE TELECOM - SOTRAPLANT</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/l_agence_telecom_-_sotraplant.png.webp?itok=TpV_hm5B</photo>
    <skippers>
      <skipper age="51">
        <nom>Matthieu FOULQUIER-GAZAGNES</nom>
        <origine>Montpellier</origine>
      </skipper>
      <skipper age="34">
        <nom>Gildas BEAUCHAMPS</nom>
        <origine>Nice</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Class40" Annee="2020">
    <nom>INTERACTION</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/interaction.jpg.webp?itok=P3vGyCpn</photo>
    <skippers>
      <skipper age="59">
        <nom>Yannig LIVORY</nom>
        <origine>Arcachon</origine>
      </skipper>
      <skipper age="56">
        <nom>Erwan LIVORY</nom>
        <origine>Arcachon</origine>
      </skipper>
    </skippers>
  </voilier>
  <voilier Classe="Class40" Annee="2021">
    <nom>EMPOWHER</nom>
    <photo>https://www.transatcafelor.org/sites/default/files/styles/crop_1800_607/public/2025-06/empowher.jpg.webp?itok=Euo0m7Ve</photo>
    <skippers>
